---

- name: filesystem | swap
  become: true
  block:
  - name: disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0
  - name: disable swap system start
    ansible.posix.mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    loop:
    - swap
    - none

- name: filesystem | journald sdcard fix
  copy: 
    content: |-
      [Journal]
      Storage=volatile
    dest: /etc/systemd/journald.conf
    mode: 0644
