---

- name: kernel | enable modules
  become: true
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
  - br_netfilter
  - overlay

- name: kernel | enable modules on boot
  become: true
  copy:
    mode: 0644
    content: "{{ item }}"
    dest: "/etc/modules-load.d/{{ item }}.conf"
  loop:
  - br_netfilter
  - overlay
