---

- name: network | sysctl
  become: true
  blockinfile:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    mode: 0644
    create: true
    block: |
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-iptables = 1
  register: sysctl_network

- name: network | reload sysctl
  become: true
  shell: sysctl -p /etc/sysctl.d/99-kubernetes-cri.conf
  when: sysctl_network.changed
