# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:L0QJ1x9jKpNx68LZ9tpj/jDXyHnFkTiKj6/5aj3BZn3G9LLQ6ai1Lg==,iv:0TZsbqw8ILSZD3va6pmUCTnb1F1xvRjxi1K7oGUUekk=,tag:JfCxhf0dOVoyOwNvExhmWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-04-16T17:28:39Z"
    mac: ENC[AES256_GCM,data:19MWPos3deVgMDQoT4i61exwlbF4tEAdS2pD6Bw1T6oeHm2Kd0JNgA0Cn36dREByxRwmvk8iXT+5tPmQmeDpienZXGCnJMt36etcHifzhOgjxACrquTCn0OHtwioX+mbMGM7vr3YOjBeh49IciYxTiySqNw9SWM+5pVrlm4BiX4=,iv:J9cCx59RV3VvaZoOWn93G6GILEcTFuaMnuSPkUGd4sQ=,tag:Q0x6kG8EfYnjR0wch5Hwww==,type:str]
    pgp:
        - created_at: "2021-04-16T17:28:38Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2j7GJlOFpKxARAAtmqlL8g74VEoANs5bstf3XsG3U4ZA80wPbCohw8d5IEl
            RMjy//RGmgkznRXkvYap6TWd06ZGzskKTBrZVq0kc6V3oY15mpweG8Pmy+lYfyXf
            IFLaC2fGdsI5catzRjJdCylFTrwYL1CQBDmPfwUATPjDGjqoN8fNvAOMzjBL4rBQ
            Mj17Tw3VucCs/54MC6ngb77/zy1t9Ge+Lk4QiY5DcGVa1oXrdqk2IUNQzQXxITnI
            zItcSxa3C9i1l8d0oXatrna7xxE1ox0MxfXSimgCPfix7daOoGgMctMela1qWsZ/
            R6e6o6b3UNmmKvjcF5ijdBy8nt4lkt22gKrTJIKM8V54NknzyxKeWCsuVNTn6meV
            vkG+KaUxxXom7SnGzhiyHC+u8PuYyygTwx+RZsYue/h3PATjxdjzI3Jeu5IzRKwo
            X9fncUMhZNgFdYGLg2T4e8HcD77wXl7PoR3ZRArNhTF9u/1PGAWicrFhcRyAJpcH
            ZuBdwqgcAUeqbK6LhJXyUd215fhTstWezPox8kjP6CTEmIucR9L96n5nxT7AZ321
            Da6t+DyX9kd2OyxtmMgXkxB7SFOSkUHdwAg2tLmNDl2DLvuhiKlY95UbFb9dnD2+
            KoZtSlNL+LvNBPG98sxc6z6Ggi9+8QgbZzaQNLl2C/YOypupO7AkCl4juk5awYTS
            XgFdMa5iDMv0fzg8jc9A/gBrsXXjKxvAH1XIFOOALwzD1THmDQFJIUniVI1XazCZ
            V5Sm9VQXbnCxpcfrdk2E8CfKD4grkaEi4YPxTKQMBvpTyGpqH+EBbG2NnNhMRSM=
            =S1c2
            -----END PGP MESSAGE-----
          fp: 556EEA05041764AC3D3AE89387872899A7BF3F64
        - created_at: "2021-04-16T17:28:38Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2SqUE71s5QKAQ//Wi+LjFPZNa+xMnZxfIcVspc9xMXZcZiTGdL+D4m5Lhaf
            x8W0JYaUPxuD2LGd7vs7PgFi4NSAbBC5fVosZLK48jBZxXujzOvlxEq9SwkBI/U1
            Bmj/YUD5g8tq5van2PF4BLQw/PbJAqpuuyY/2E6dsjWNrxF+TZX85FH9qDKgP4n2
            ZDPwW6ebrOZccZ2hYUFrMcp9KXVHPhb50y9Klv5I6oi8x27q8tCnrRQvY4gHd7qK
            y8PmwiqzwU6VsHbIvpm0AMCTJJMwh/Fu47EfKsLxBNGyGrF98gqEdu/PJkqlA8G3
            CVZm8Oh2VAskBEKMlsL93tHauWIfXu8y+tqdWJd4kY4LYNUJI2YCfhbZ731Yoott
            4kjMb4xqlUqGBETXdb89nwWSUk6LRSKWUjzxwleKCmdJc/WO1A6wOuUVyNzSyTFs
            Q4nMn5SOAgbaQRWLD1wkaoPDkE8H+yDvgv1JB4tenM4l78L9vlLjgmI8zNIpxkNo
            HJ4Wqu7UnE4h2W8SQKPPmoCZtlea5pEUznuHByU3yLPa9EpyQkULYWCC/TpRgLeG
            3/35BEPzUUy9tAXqZb7xcpxf6kXHuYY2hTl8sr/+eMFj5XOKGETNcIWbgDb4RMWf
            wLRR1eLoWIr956UZGnqf5StCaoxTZCo3h+s4qOicEODhiS4EzRnNEpcz5hHb5Y3S
            XgF6Ku/uhm+vQJH2bQam+ZMkcOU+gwRPX18AFM/kFSrRZANnJ0NUtjuq1q3mmDbP
            uPuZ+qlQKP2j/KkMrieAqANCm6AwdFDdScfcicaOb5FFhiot1nxpDHB5YBqBPkE=
            =MiYL
            -----END PGP MESSAGE-----
          fp: FFF8C1792512008267BFD5291B7C06C8711C5E97
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
